CREATE TABLE [dbo].[tbCustomer] (
    [CID]                               INT            NOT NULL,
    [CustomerID]                        CHAR (50)      NOT NULL,
    [BookId]                            INT            NOT NULL,
    [NameLast]                          VARCHAR (30)   NULL,
    [NameFirst]                         VARCHAR (30)   NULL,
    [NameMI]                            CHAR (1)       NULL,
    [Address]                           VARCHAR (180)  NULL,
    [City]                              VARCHAR (100)  NULL,
    [State]                             CHAR (2)       NULL,
    [Zip]                               VARCHAR (15)   NULL,
    [Country]                           VARCHAR (30)   NULL,
    [EMail]                             VARCHAR (40)   NULL,
    [HomePhone]                         VARCHAR (25)   NULL,
    [BusinessPhone]                     VARCHAR (25)   NULL,
    [Fax]                               VARCHAR (25)   NULL,
    [Password]                          VARCHAR (20)   NULL,
    [ParlayName]                        CHAR (25)      NULL,
    [AgentID]                           VARCHAR (50)   NULL,
    [OpenedBy]                          VARCHAR (50)   NULL,
    [CreditLimit]                       FLOAT (53)     CONSTRAINT [DF_tbCustomer_CreditLimit] DEFAULT ((0)) NULL,
    [Comments]                          VARCHAR (MAX)  NULL,
    [Active]                            CHAR (1)       NULL,
    [AccessedBy]                        CHAR (50)      NULL,
    [LastVerDateTime]                   DATETIME       NULL,
    [LastVerDocumentNumber]             INT            NULL,
    [LastVerBalance]                    FLOAT (53)     CONSTRAINT [DF_tbCustomer_LastVerBalance] DEFAULT ((0)) NULL,
    [CommentsForTW]                     VARCHAR (MAX)  NULL,
    [PercentBook]                       INT            CONSTRAINT [DF_tbCustomer_PercentBook] DEFAULT ((0)) NULL,
    [WagerLimit]                        FLOAT (53)     CONSTRAINT [DF_tbCustomer_WagerLimit] DEFAULT ((0)) NULL,
    [StaticLinesFlag]                   CHAR (1)       NULL,
    [CreditAcctFlag]                    CHAR (1)       NULL,
    [BaseballAction]                    VARCHAR (10)   NULL,
    [UsePuckLineFlag]                   CHAR (1)       NULL,
    [PayoutPassword]                    VARCHAR (20)   NULL,
    [LastCallDateTime]                  DATETIME       NULL,
    [Source]                            VARCHAR (255)  NULL,
    [Promoter]                          VARCHAR (255)  NULL,
    [ReferredBy]                        VARCHAR (255)  NULL,
    [IntFootballFlag]                   CHAR (1)       NULL,
    [IntBasketballFlag]                 CHAR (1)       NULL,
    [IntHockeyFlag]                     CHAR (1)       NULL,
    [IntBaseballFlag]                   CHAR (1)       NULL,
    [IntHorsesFlag]                     CHAR (1)       NULL,
    [IntOtherFlag]                      CHAR (1)       NULL,
    [EstWager5to50Flag]                 CHAR (1)       NULL,
    [EstWager51to100Flag]               CHAR (1)       NULL,
    [EstWager101to500Flag]              CHAR (1)       NULL,
    [EstWager501to1000Flag]             CHAR (1)       NULL,
    [EstWagerOver1000Flag]              CHAR (1)       NULL,
    [ZeroBalanceFlag]                   CHAR (1)       NULL,
    [Currency]                          VARCHAR (60)   NULL,
    [CurrentBalance]                    FLOAT (53)     CONSTRAINT [DF_tbCustomer_CurrentBalance_1] DEFAULT ((0)) NULL,
    [LastInsDocumentNumber]             INT            NULL,
    [PendingWagerBalance]               FLOAT (53)     CONSTRAINT [DF_tbCustomer_PendingWagerBalance_1] DEFAULT ((0)) NULL,
    [PendingWagerCount]                 INT            CONSTRAINT [DF_tbCustomer_PendingWagerCount_1] DEFAULT ((0)) NULL,
    [VigDiscountExpDate]                DATETIME       NULL,
    [VigDiscountPercent]                INT            CONSTRAINT [DF_tbCustomer_VigDiscountPercent_1] DEFAULT ((0)) NULL,
    [InetVigDiscountExpDate]            DATETIME       NULL,
    [InetVigDiscountPercent]            INT            CONSTRAINT [DF_tbCustomer_InetVigDiscountPercent_1] DEFAULT ((0)) NULL,
    [OpenDateTime]                      DATETIME       NULL,
    [NoMailFlag]                        CHAR (1)       NULL,
    [NoEmailFlag]                       CHAR (1)       NULL,
    [NoPhoneFlag]                       CHAR (1)       NULL,
    [InetTarget]                        VARCHAR (40)   NULL,
    [LossCap]                           FLOAT (53)     CONSTRAINT [DF_tbCustomer_LossCap_1] DEFAULT ((0)) NULL,
    [ShaveFbHalfPoint]                  CHAR (1)       NULL,
    [ShaveBbHalfPoint]                  CHAR (1)       NULL,
    [ApplyDetailWagerLimitsFlag]        CHAR (1)       NULL,
    [EnforceAccumWagerLimitsFlag]       CHAR (1)       NULL,
    [ParlayMaxBet]                      FLOAT (53)     CONSTRAINT [DF_tbCustomer_ParlayMaxBet_1] DEFAULT ((0)) NULL,
    [ParlayMaxPayout]                   FLOAT (53)     CONSTRAINT [DF_tbCustomer_ParlayMaxPayout_1] DEFAULT ((0)) NULL,
    [HorseMaxBet]                       FLOAT (53)     CONSTRAINT [DF_tbCustomer_HorseMaxBet_1] DEFAULT ((0)) NULL,
    [HorseMaxPayout]                    FLOAT (53)     CONSTRAINT [DF_tbCustomer_HorseMaxPayout_1] DEFAULT ((0)) NULL,
    [TeaserMaxBet]                      FLOAT (53)     CONSTRAINT [DF_tbCustomer_TeaserMaxBet_1] DEFAULT ((0)) NULL,
    [ContestMaxBet]                     FLOAT (53)     CONSTRAINT [DF_tbCustomer_ContestMaxBet] DEFAULT ((0)) NULL,
    [AgentType]                         CHAR (1)       NULL,
    [HalfPointCuBasketballFlag]         CHAR (1)       NULL,
    [HalfPointCuBasketballDow]          INT            CONSTRAINT [DF_tbCustomer_HalfPointCuBasketballDow] DEFAULT ((0)) NULL,
    [HalfPointInetBasketballFlag]       CHAR (1)       NULL,
    [HalfPointInetBasketballDow]        INT            CONSTRAINT [DF_tbCustomer_HalfPointInetBasketballDow] DEFAULT ((0)) NULL,
    [HalfPointCuFootballFlag]           CHAR (1)       NULL,
    [HalfPointCuFootballDow]            INT            CONSTRAINT [DF_tbCustomer_HalfPointCuFootballDow] DEFAULT ((0)) NULL,
    [HalfPointInetFootballFlag]         CHAR (1)       NULL,
    [HalfPointInetFootballDow]          INT            CONSTRAINT [DF_tbCustomer_HalfPointInetFootballDow] DEFAULT ((0)) NULL,
    [HalfPointMaxBet]                   FLOAT (53)     CONSTRAINT [DF_tbCustomer_HalfPointMaxBet] DEFAULT ((0)) NULL,
    [InstantActionFlag]                 CHAR (1)       NULL,
    [CommentsForCustomer]               VARCHAR (MAX)  NULL,
    [CarryOverAmount]                   FLOAT (53)     CONSTRAINT [DF_tbCustomer_CarryOverAmount_1] DEFAULT ((0)) NULL,
    [WeeklyLimitFlag]                   CHAR (1)       NULL,
    [SettleFigure]                      FLOAT (53)     CONSTRAINT [DF_tbCustomer_SettleFigure] DEFAULT ((0)) NULL,
    [ConfirmationDelay]                 INT            CONSTRAINT [DF_tbCustomer_ConfirmationDelay] DEFAULT ((0)) NULL,
    [EasternLineFlag]                   CHAR (1)       NULL,
    [TempCreditAdj]                     FLOAT (53)     CONSTRAINT [DF_tbCustomer_TempCreditAdj_1] DEFAULT ((0)) NULL,
    [TempCreditAdjExpDate]              DATETIME       NULL,
    [FreePlayBalance]                   FLOAT (53)     CONSTRAINT [DF_tbCustomer_FreePlayBalance_1] DEFAULT ((0)) NULL,
    [FreePlayPendingBalance]            FLOAT (53)     CONSTRAINT [DF_tbCustomer_FreePlayPendingBalance_1] DEFAULT ((0)) NULL,
    [FreePlayPendingCount]              INT            CONSTRAINT [DF_tbCustomer_FreePlayPendingCount_1] DEFAULT ((0)) NULL,
    [AutoAgentShadeGroupFlag]           CHAR (1)       NULL,
    [CUMinimumWager]                    INT            CONSTRAINT [DF_tbCustomer_CUMinimumWager_1] DEFAULT ((0)) NULL,
    [InetMinimumWager]                  INT            CONSTRAINT [DF_tbCustomer_InetMinimumWager_1] DEFAULT ((0)) NULL,
    [CasinoActive]                      CHAR (1)       NULL,
    [TimeZone]                          INT            CONSTRAINT [DF_tbCustomer_TimeZone_1] DEFAULT ((0)) NULL,
    [EnableRifFlag]                     CHAR (1)       NULL,
    [LimitRifToRiskFlag]                CHAR (1)       NULL,
    [WiseActionFlag]                    CHAR (1)       NULL,
    [EnforceAccumWagerLimitsByLineFlag] CHAR (1)       NULL,
    [PriceType]                         CHAR (1)       CONSTRAINT [DF__tbCustome__Price__23B4F316] DEFAULT ('A') NULL,
    [LastchangedBy]                     VARCHAR (50)   NULL,
    [ZeroBalPositiveOnlyFlag]           VARCHAR (1)    CONSTRAINT [DF_tbCustomer_ZeroBalPositiveOnlyFlag] DEFAULT (NULL) NULL,
    [TempWagerLimit]                    FLOAT (53)     NULL,
    [TempWagerLimitExpiration]          DATETIME       NULL,
    [LastWagerDateTime]                 DATETIME       NULL,
    [EnforceParlayMaxBetFlag]           CHAR (1)       NULL,
    [EnforceTeaserMaxBetFlag]           CHAR (1)       NULL,
    [SessionID]                         CHAR (36)      NULL,
    [SessionLastActivity]               DATETIME       NULL,
    [FavoriteSport]                     VARCHAR (20)   NULL,
    [FavoriteSportSubType]              VARCHAR (30)   NULL,
    [FavoriteTeamID]                    VARCHAR (40)   NULL,
    [WebLanguage]                       VARCHAR (3)    NULL,
    [WebHomePage]                       VARCHAR (20)   NULL,
    [WebPitcherOption]                  CHAR (10)      NULL,
    [WebRememberPassword]               BIT            NULL,
    [ShowLinesUpdIndicator]             BIT            NULL,
    [CanControlCasinosAccess]           BIT            NULL,
    [LiveBettingAccepted]               BIT            NULL,
    [ShowInetCustomerPassword]          BIT            NULL,
    [HalfPointWagerLimitFlag]           CHAR (1)       NULL,
    [HalfPointFootballOn3Flag]          CHAR (1)       NULL,
    [HalfPointFootballOff3Flag]         CHAR (1)       NULL,
    [HalfPointFootballOn7Flag]          CHAR (1)       NULL,
    [HalfPointFootballOff7Flag]         CHAR (1)       NULL,
    [HalfPointDenyTotalsFlag]           CHAR (1)       NULL,
    [LastUpdateDateTime]                DATETIME       NULL,
    [CustomerIsABot]                    BIT            NULL,
    [AdditionalComments1]               VARCHAR (MAX)  NULL,
    [AdditionalComments2]               VARCHAR (MAX)  NULL,
    [AdditionalComments3]               VARCHAR (MAX)  NULL,
    [AdditionalComments4]               VARCHAR (MAX)  NULL,
    [AdditionalComments5]               VARCHAR (MAX)  NULL,
    [ShowBetSlipInWebSite]              BIT            NULL,
    [MaxProfitPerWeek]                  FLOAT (53)     NULL,
    [MaxWeeksDFAndPerformance]          INT            NULL,
    [CommentsForCstExpDate]             DATETIME       NULL,
    [CommentsForTWExpDate]              DATETIME       NULL,
    [ContestMaxPayout]                  FLOAT (53)     NULL,
    [NotifyBetsToAgent]                 BIT            NULL,
    [CashierActivated]                  BIT            CONSTRAINT [DF_tbCustomer_CashierActivated] DEFAULT ((0)) NULL,
    [ActionReverseMaxBet]               FLOAT (53)     NULL,
    [MaxMoneyLinePrice]                 INT            NULL,
    [MaxContestPrice]                   INT            NULL,
    [EncryptedPassword]                 BINARY (64)    NULL,
    [PasswordKey]                       NVARCHAR (36)  NULL,
    [LoginID]                           NVARCHAR (50)  NULL,
    [IsGeoFenceCountryState]            BIT            NULL,
    [TemporalToken]                     NCHAR (16)     NULL,
    [TemporalTokenDateTime]             DATETIME       NULL,
    [ParlaysPayWithTrueOdds]            BIT            NULL,
    [IsAffiliate]                       BIT            NULL,
    [CustomerBirthDate]                 DATETIME       NULL,
    [PromoCode]                         VARCHAR (150)  NULL,
    [CMAccessedBy]                      CHAR (50)      NULL,
    [AdditionalComments6]               VARCHAR (MAX)  NULL,
    [AdditionalComments7]               VARCHAR (MAX)  NULL,
    [AutoRebateCasino]                  BIT            NULL,
    [Address2]                          NVARCHAR (180) NULL,
    [AdditionalComments8]               VARCHAR (MAX)  NULL,
    [DailyWagerLimit]                   FLOAT (53)     NULL,
    [WeeklyWagerLimit]                  FLOAT (53)     NULL,
    [MonthlyWagerLimit]                 FLOAT (53)     NULL,
    [Ssn]                               INT            NULL,
    [Gender]                            CHAR (1)       NULL,
    [POSTaxPercent]                     FLOAT (53)     NULL,
    [IfBetMaxBet]                       FLOAT (53)     NULL,
    [IfBetMaxPayout]                    FLOAT (53)     NULL,
    [RoundRobinMaxBet]                  FLOAT (53)     NULL,
    [RoundRobinMaxPayout]               FLOAT (53)     NULL,
    [NotifyBetsToAgentAmt]              FLOAT (53)     NULL,
    [EnforceAccumWagerLimitsMode]       CHAR (1)       NULL,
    [Score]                             INT            NULL,
    [ChangePasswordRequired]            BIT            NULL,
    [LastChangePasswordRequiredDT]      DATETIME       NULL,
    [IsOutSourced]                      BIT            NULL,
    [Id_bonus_plan]                     INT            NULL,
    [LastDepositDateTime]               DATETIME       NULL,
    [FirstDepositDateTime]              DATETIME       NULL,
    [CommentsForCustomerHidden]         BIT            NULL,
    [AuthProvider]                      NVARCHAR (50)  CONSTRAINT [DF__tbCustome__AuthP__07C12930] DEFAULT ('local') NOT NULL,
    [AcceptMarketingPromotions]         BIT            CONSTRAINT [DF__tbCustome__Accep__08B54D69] DEFAULT ((1)) NOT NULL,
    CONSTRAINT [PK_tbCustomer__CustomerID] PRIMARY KEY CLUSTERED ([CustomerID] ASC) WITH (FILLFACTOR = 80)
);


GO
ALTER TABLE [dbo].[tbCustomer] SET (LOCK_ESCALATION = AUTO);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Used by Doughflow integration', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'tbCustomer', @level2type = N'COLUMN', @level2name = N'CashierActivated';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'tbCustomer', @level2type = N'COLUMN', @level2name = N'CurrentBalance';

