CREATE TABLE [dbo].[tbWagerContestItem] (
    [TicketNumber]            INT           NOT NULL,
    [WagerNumber]             INT           NOT NULL,
    [ItemNumber]              INT           NOT NULL,
    [ContestNum]              INT           NULL,
    [ContestDateTime]         DATETIME      NULL,
    [ContestDesc]             VARCHAR (500) NULL,
    [ContestantName]          CHAR (50)     NULL,
    [Outcome]                 CHAR (1)      NULL,
    [FinalMoney]              FLOAT (53)    NULL,
    [FinalToBase]             FLOAT (53)    NULL,
    [AmountWagered]           FLOAT (53)    NULL,
    [ToWinAmount]             FLOAT (53)    NULL,
    [OriginalMoney]           FLOAT (53)    NULL,
    [OriginalToBase]          FLOAT (53)    NULL,
    [GradeNum]                INT           NULL,
    [Store]                   CHAR (20)     NULL,
    [CustProfile]             CHAR (20)     NULL,
    [FinalAmountWagered]      FLOAT (53)    NULL,
    [FinalAmountWon]          FLOAT (53)    NULL,
    [WinPlaceOrShow]          CHAR (1)      NULL,
    [OriginatingTicketNumber] INT           NULL,
    [XtoYLineRep]             CHAR (1)      NULL,
    [ThresholdType]           CHAR (1)      NULL,
    [ThresholdUnits]          VARCHAR (20)  NULL,
    [ThresholdLine]           FLOAT (53)    NULL,
    [ContestType]             CHAR (50)     NULL,
    [ContestType2]            CHAR (50)     NULL,
    [ContestType3]            CHAR (50)     NULL,
    [ContestantNum]           INT           NULL,
    [GradeToWinAmount]        FLOAT (53)    NULL,
    [PercentBook]             INT           NULL,
    [VolumeAmount]            FLOAT (53)    NULL,
    [ShowOnChartFlag]         CHAR (1)      NULL,
    [DailyFigureDate]         DATETIME      NULL,
    [CurrencyCode]            CHAR (3)      NULL,
    [ValueDate]               DATETIME      NULL,
    [ArchiveFlag]             CHAR (1)      NULL,
    [LayoffFlag]              CHAR (1)      NULL,
    [AgentID]                 VARCHAR (50)  NULL,
    [FreePlayFlag]            CHAR (1)      NULL,
    [WiseActionFlag]          CHAR (1)      NULL,
    [FinalDecimal]            FLOAT (53)    NULL,
    [FinalNumerator]          INT           NULL,
    [FinalDenominator]        INT           NULL,
    [OriginalDecimal]         FLOAT (53)    NULL,
    [OriginalNumerator]       INT           NULL,
    [OriginalDenominator]     INT           NULL,
    [PriceType]               CHAR (1)      DEFAULT ('A') NULL,
    [AhResultFlag]            CHAR (1)      NULL,
    [WinRatio]                FLOAT (53)    DEFAULT ((1.0)) NULL,
    [WageringMode]            CHAR (1)      NULL,
    [LastEditedBy]            VARCHAR (50)  NULL,
    [LastEditedByOn]          DATETIME      NULL,
    CONSTRAINT [PK_tbWagerContestItem_1__27] PRIMARY KEY CLUSTERED ([TicketNumber] ASC, [WagerNumber] ASC, [ItemNumber] ASC) WITH (FILLFACTOR = 80)
);

