CREATE TABLE [dbo].[tbWagerGameItem] (
    [TicketNumber]            INT          NOT NULL,
    [WagerNumber]             INT          NOT NULL,
    [ItemNumber]              INT          NOT NULL,
    [GameNum]                 INT          NULL,
    [GameDateTime]            DATETIME     NULL,
    [SportType]               CHAR (20)    NULL,
    [SportSubType]            CHAR (30)    NULL,
    [WagerType]               CHAR (1)     NULL,
    [AdjSpread]               FLOAT (53)   NULL,
    [AdjTotalPoints]          FLOAT (53)   NULL,
    [TotalPointsOU]           CHAR (1)     NULL,
    [FinalMoney]              INT          NULL,
    [ChosenTeamID]            VARCHAR (85) NULL,
    [Outcome]                 CHAR (1)     NULL,
    [AmountWagered]           FLOAT (53)   NULL,
    [ToWinAmount]             FLOAT (53)   NULL,
    [TeaserPoints]            FLOAT (53)   NULL,
    [GradeNum]                INT          NULL,
    [Store]                   CHAR (20)    NULL,
    [CustProfile]             CHAR (20)    NULL,
    [PeriodNumber]            INT          NULL,
    [PeriodDescription]       CHAR (20)    NULL,
    [FinalAmountWagered]      FLOAT (53)   NULL,
    [FinalAmountWon]          FLOAT (53)   NULL,
    [OriginatingTicketNumber] INT          NULL,
    [AdjustableOddsFlag]      CHAR (1)     NULL,
    [ListedPitcher1]          VARCHAR (40) NULL,
    [ListedPitcher2]          VARCHAR (40) NULL,
    [Pitcher1ReqFlag]         CHAR (1)     NULL,
    [Pitcher2ReqFlag]         CHAR (1)     NULL,
    [GradeMoney]              INT          NULL,
    [GradeToWinAmount]        FLOAT (53)   NULL,
    [PercentBook]             INT          NULL,
    [VolumeAmount]            FLOAT (53)   NULL,
    [ShowOnChartFlag]         CHAR (1)     NULL,
    [DailyFigureDate]         DATETIME     NULL,
    [CurrencyCode]            CHAR (3)     NULL,
    [ValueDate]               DATETIME     NULL,
    [ArchiveFlag]             CHAR (1)     NULL,
    [LayoffFlag]              CHAR (1)     NULL,
    [AgentID]                 VARCHAR (50) NULL,
    [EasternLine]             FLOAT (53)   NULL,
    [FreePlayFlag]            CHAR (1)     NULL,
    [WiseActionFlag]          CHAR (1)     NULL,
    [OrigSpread]              FLOAT (53)   NULL,
    [OrigTotalPoints]         FLOAT (53)   NULL,
    [OrigMoney]               INT          NULL,
    [FinalDecimal]            FLOAT (53)   NULL,
    [FinalNumerator]          INT          NULL,
    [FinalDenominator]        INT          NULL,
    [OrigDecimal]             FLOAT (53)   NULL,
    [OrigNumerator]           INT          NULL,
    [OrigDenominator]         INT          NULL,
    [PriceType]               CHAR (1)     DEFAULT ('A') NULL,
    [GradeDecimal]            FLOAT (53)   NULL,
    [GradeNumerator]          INT          NULL,
    [GradeDenominator]        INT          NULL,
    [AhResultFlag]            CHAR (1)     NULL,
    [FreeHalfPointGiven]      BIT          NULL,
    [WageringMode]            CHAR (1)     NULL,
    [LastEditedBy]            VARCHAR (50) NULL,
    [LastEditedByOn]          DATETIME     NULL,
    CONSTRAINT [PK_tbWagerGameItem__TicketNumber_WagerNumber_ItemNum] PRIMARY KEY CLUSTERED ([TicketNumber] ASC, [WagerNumber] ASC, [ItemNumber] ASC) WITH (FILLFACTOR = 90)
);

