CREATE TABLE [dbo].[tbWager] (
    [TicketNumber]            INT            NOT NULL,
    [WagerNumber]             INT            NOT NULL,
    [AmountWagered]           FLOAT (53)     CONSTRAINT [DF__tbWager__AmountW__048FB6CA] DEFAULT ((0)) NULL,
    [WagerType]               CHAR (1)       NULL,
    [AmountWon]               FLOAT (53)     NULL,
    [WagerStatus]             CHAR (1)       NULL,
    [TeaserName]              CHAR (25)      NULL,
    [Description]             VARCHAR (MAX)  NULL,
    [ToWinAmount]             FLOAT (53)     CONSTRAINT [DF__tbWager__ToWinAm__0583DB03] DEFAULT ((0)) NULL,
    [ParlayName]              CHAR (25)      NULL,
    [MinimumPicks]            INT            NULL,
    [Ties]                    INT            CONSTRAINT [DF__tbWager__Ties__0677FF3C] DEFAULT ((0)) NULL,
    [GradeNum]                INT            NULL,
    [TotalPicks]              INT            NULL,
    [RoundRobinLink]          INT            NULL,
    [ARLink]                  INT            NULL,
    [ARBirdcageLink]          INT            NULL,
    [Comments]                VARCHAR (MAX)  NULL,
    [DiscrepancyFlag]         CHAR (1)       NULL,
    [CreditAcctFlag]          CHAR (1)       NULL,
    [ContinueOnPushFlag]      CHAR (1)       NULL,
    [PlayNumber]              INT            NULL,
    [AmountRefunded]          FLOAT (53)     NULL,
    [AcceptedDateTime]        DATETIME       NULL,
    [AmountLost]              FLOAT (53)     NULL,
    [GradeDateTime]           DATETIME       NULL,
    [DailyFigureDate]         DATETIME       NULL,
    [CurrencyCode]            CHAR (3)       NULL,
    [ValueDate]               DATETIME       NULL,
    [ArchiveFlag]             CHAR (1)       NULL,
    [BoxLink]                 INT            NULL,
    [LayoffFlag]              CHAR (1)       NULL,
    [MaxPayout]               FLOAT (53)     NULL,
    [ParlayPayoutType]        CHAR (1)       NULL,
    [FreePlayFlag]            CHAR (1)       NULL,
    [RifBackwardTicketNumber] INT            NULL,
    [RifBackwardWagerNumber]  INT            NULL,
    [RifForwardTicketNumber]  INT            NULL,
    [RifForwardWagerNumber]   INT            NULL,
    [RifForwardAmountWagered] FLOAT (53)     NULL,
    [RifWinOnlyFlag]          CHAR (1)       NULL,
    [RifNoActionFlag]         CHAR (1)       NULL,
    [RifCurrentPlayFlag]      CHAR (1)       NULL,
    [RifForwardWinOnlyFlag]   CHAR (1)       NULL,
    [LastEditedBy]            VARCHAR (50)   NULL,
    [LastEditedByOn]          DATETIME       NULL,
    [ReferenceNumber]         VARCHAR (21)   NULL,
    [POSisPaid]               BIT            NULL,
    [POSData]                 NVARCHAR (100) NULL,
    [POSPaidTimeStamp]        DATETIME       NULL,
    [POSOtherData]            INT            NULL,
    [Unconfirmed]             BIT            NULL,
    CONSTRAINT [PK_tbWager__TicketNumber_WagerNumber] PRIMARY KEY CLUSTERED ([TicketNumber] ASC, [WagerNumber] ASC) WITH (FILLFACTOR = 80)
);

